# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa22c87758cd7a6a0564d43efaf771962a3aed0a701962b65a398351f4f0d149adcdba0bbf2f7a95172895ba6930c5c941a6b5f9a82a4df407168514a71f33c6

test:
  secret_key_base: d7c21fbfb08acc955bd43ec6bf784da34837dab6bca837121c7eca6efccde56d9a6c0b3964416e56ab5eff6362e7287b91d7f904bc7f899d912a078c54901835

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
